### ISSUE TITLE
[FEATURE] GNOME 47 support

### ISSUE THREAD

**Issue by bubner** [G-dH/advanced-alttab-window-switcher#122]
GNOME 47 was officially released yesterday

**Comment by G-dH** [comment]
You can install AATWS from this repository. I appreciate any feedback.

**Comment by andreabenini** [comment]
I'm now using this directly from the repo and it looks fine. As a note I suggest you to recompile and create a new zip from it. Latest available download: `advanced-alt-tab@G-dH.github.com.zip` you mentioned in the README.md file does not includes v47 in the `metadata.json` file because it's from May'24.

**Comment by G-dH** [comment]
@andreabenini Thanks and sorry for the late response. I'll add the release soon.
