### ISSUE TITLE
Show Workspace Pop-up and Toggle Activities Overview

### ISSUE THREAD

**Issue by zz0rk** [G-dH/advanced-alttab-window-switcher#19]
I recently upgraded to the latest version.

I have two issues.

1. Toggle Activities Overview no longer works. When I press Super > Shift + Super it won't toggle Activities Overview but instead toggles between Windows and Application Switcher.

2. This actually may not be an issue, but a feature that has been removed. Under Misc the option to disable Show Workspace Pop-up is no longer present. I very much preferred the pop-up be disabled.

Thank you

MISSING from the most current version as far as I can tell:
![image](https://user-images.githubusercontent.com/18619265/161451399-161a6c14-50aa-4d2a-94a7-3ca64f50089b.png)

**Comment by G-dH** [comment]
Thank you for the feedback!
I'm sorry, I've changed the shortcut because I found that switching filter and switcher mode is more helpful for me. In the latest version you can use `Ctrl+Shift+Super` to toggle the Overview.
I've also removed all workspace switcher options and moved them, and added much more, to another extension `Workspace Switcher Manager` in order to synchronize my modifications of the switcher popup and all workspace related settings system wide. If you want to remove the popup entirely, this extension can also do it. And maybe you'll find that you can use the WSM extension to make the popup less intrusive or even useful.

Feel free to let me know about your suggestions.

**Comment by zz0rk** [comment]
Thank you, I was aware of the Ctrl+Shift+Super option. It's just that it's one more key and selecting all three is a bit awkward, at least for me. I've checked out WSM but unfortunately it doesn't add any value to my workflow. Thank you though. Cheers

**Comment by G-dH** [comment]
OK, I'll give you the shortcut back and also add the workspace pop-up option.

**Comment by zz0rk** [comment]
Oh, that's great. It worked. Thank you!
