### ISSUE TITLE
[FEATURE REQUEST] Hot Key to toggle between running apps and favorite apps

### ISSUE THREAD

**Issue by benintech** [G-dH/advanced-alttab-window-switcher#30]
Great tool !
A suggestion : Having the favorites in the app list is convenient, but it also bloats the app list. A nice feature would be to show the favorites separately, on demand, with a hot key (for example F, to toggle between the running apps list and the favorites list).

**Comment by G-dH** [comment]
I've added an option to include Show Apps Icon to the app list and now if you select the icon, you can toggle the Include favorites option on/off by pressing the key above Tab / group switcher shortcut.
But in most cases it's much faster to enter the first one or two characters of the name of the app you're about to launch in search mode to get directly to the app launcher instead of using hotkey to show favorites and ....

**Comment by G-dH** [comment]
>Not working on my setup (GS 3.38). Pressing the key above tab while the "Show Applications" icon is selected has no effect (pressing this key on an opened application opens the windows switcher for that app). 

It was released today, but the implementation was not well done so had fix it.

>Besides, first having to select the show applications and then press a key in order to show/hide the favorites seems a little bit cumbersome : why not simply toggle between opened apps and favorites with a plain shortcut ?

Switching this option using F hotkey is actually more cumbersome for me than pressing End ore arrow left followed by the key above Tab, that's why I've implemented this. But the truth is that I will never use it anyway because search mode is giving me direct shortcuts to all applications. So, maybe later, I'll keep it open.

**Comment by G-dH** [comment]
Default hotkey for `Include Favorite Apps` has been set to 'O' since 'F' is already used for Fullscreen. You can change this in Settings.
