### ISSUE TITLE
[BUG] switch-window-backwards key does not work on gnome-shell 45

### ISSUE THREAD

**Issue by tpikonen** [G-dH/advanced-alttab-window-switcher#85]
**Describe the bug**

I have the 'switch-window-backwards' key set to `['<Alt>Above_Tab']` in dconf at /org/gnome/desktop/wm/keybindings. This used to work in AAWS with gnome-shell 44, but after upgrading to 45 it stopped working. It still works on the stock gnome-shell window switcher, if I disable this extension.

**To Reproduce**

1. Set 'switch-window-backwards' to some key
2. Try to use the key to move backwards in the alt-tab window list
3. The keybinding does not do anything

**Expected behavior**

Move forward in the window list with alt-tab, move backwards with alt-Above_tab.

**Desktop (please complete the following information):**
 - OS: Debian trixie, gnome-shell 45.2 from experimental
 - Version of the extension: 45.6
 - Source of installation: extension.gnome.org

**Comment by G-dH** [comment]
Seems like I fixed one issue and created another one.. Thanks for reporting this.

**Comment by G-dH** [comment]
Turned out the issue was that I didn't notice a change in the arguments of the `global.display.get_keybinding_action()` method in GS 45. Fixed in `main`, I'll update the e.g.o package soon.

**Comment by lvanderree** [comment]
I've upgraded 21 commits ( 5a5b805..2166b95 ) and now with the `Switch windows of an application` it now is possible again to press the switch key (in my case ALT + backtick) more than once! I can also go backwards  (ALT + SHIFT + backtick)  again!  Great!

However, when I am in the `Switch windows of an application`-screen, and I press `switch windows` (ALT + (SHIFT + ) TAB), I leave the  `Switch windows of an application`-screen , which I would like to have stayed in (just like the other way around, when I am in `switch windows`-screen via ALT+TAB and press ALT+backtick I stay in `switch windows`). However I don't get the `switch windows`-screen either, but I get the `switch application`-screen, that I don't have setup to show up, and don't want to see either way. Is this some misconfiguration on my side, or intentional, or maybe a (new) bug?

**Comment by G-dH** [comment]
@lvanderree

`Switch windows of an application` is logically a part of the app switcher. Therefore, the Tab key switches you to the app mode, allowing you to switch to another app.

In the window switcher mode, the backtick key allows you to switch between applications while staying in the window switcher mode. It groups the listed windows by apps and switches between the first windows of each app. I initially created the switcher for windows only, providing the capability to switch between apps using this approach.

**Comment by lvanderree** [comment]
@G-dH Thank you for your fast reply and insights in how it was designed.

I've just confirmed that backticking in window-switcher-mode rearranges the windows per app. I did not notice that yet, but nice done!

Then we can keep this issue closed, and I have to be more careful not accidentally pressing TAB when switching windows within an app.
